#! /bin/bash

for alpha1 in $(seq 8 0.2 10); do
    for alpha2 in $(seq -1 0.2 3); do
        echo -n "$alpha1: "
        echo -n "$alpha2: "
        scripts/run_vad.sh $alpha1 $alpha2 | grep TOTAL
    done
done