#! /bin/bash

for alpha1 in $(seq 5 0.5 8); do
    for alpha2 in $(seq 0 0.5 3); do
        echo -n "$alpha1: "
        echo -n "$alpha2: "
        scripts/run_vad.sh $alpha1 $alpha2 | grep TOTAL
    done
done