#! /bin/bash

for alpha1 in $(seq 5 0.5 8.5); do
    for alpha2 in $(seq 5 0.5 $alpha1); do
    echo -n "$alpha1: "
    echo -n "$alpha2: "
    scripts/run_vad.sh $alpha1 $alpha2 | grep TOTAL
    done
done